<a href="https://colab.research.google.com/github/ramesitexp/Python_Zone/blob/main/NumbyOperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
1+1

2

In [2]:
#Numpy
import numpy as np

In [4]:
lst=[1,2,3,4]
arr=np.array(lst)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(4,)

In [9]:
arr1=np.array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr1.shape

(2, 3)

In [11]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [16]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [17]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [22]:
dic=np.array({"Ram":25,"Raj":27})

In [20]:
arr1.dtype

dtype('int64')

In [23]:
dic.dtype

dtype('O')

In [24]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [33]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [35]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [37]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [47]:
np.linspace(1,20,40).reshape(2,20)

array([[ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
         3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
         5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
         8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026],
       [10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
        13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
        15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
        18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ]])

In [49]:
np.zeros(10).reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [55]:
np.ones((5,2,8)).reshape(8,10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [56]:
5+np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [59]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [60]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
print("Random number generation (Uniform distribution)")
np.random.rand(2,3)

Random number generation (Uniform distribution)


array([[0.26374805, 0.61219227, 0.83826949],
       [0.01711097, 0.35391414, 0.80118433]])

In [63]:
print("Random number following a Normal distribution with mean=0 and std=1")
print(np.random.randn(5,3))

Random number following a Normal distribution with mean=0 and std=1
[[-0.79701098  0.40114916  1.5822982 ]
 [-0.58503386 -0.70665837  0.27004842]
 [ 0.21222657 -0.68959917 -1.24901766]
 [-0.80138033 -0.77061971 -0.38310573]
 [ 1.60549131 -0.34183053  1.63513136]]


In [74]:
np.random.randint(1,100)

18

In [79]:
np.random.randint(1,100,50)

array([21, 18, 26, 39, 64, 75, 14, 20, 60, 33, 86, 41, 93, 82, 91, 65, 70,
       95, 80, 48,  2, 21, 70, 71, 20,  6, 64, 14, 49,  7,  1, 93, 60, 17,
       29, 49, 48, 79, 22, 43, 97,  7, 36, 79,  1, 11, 12, 17, 83, 41])

In [80]:
np.random.randint(1,100,(4,4))

array([[84, 50, 21, 44],
       [14, 54, 93, 21],
       [ 6, 77, 90, 79],
       [36, 10, 25, 23]])

In [81]:
arr=np.arange(0,11)

In [85]:
##slicing
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [87]:
arr[-1]

10

In [88]:
arr[-7]

4

In [89]:
arr[-1:7:-1]

array([10,  9,  8])

In [91]:
arr[-1:3]

array([], dtype=int64)

In [92]:
arr[-1:3:-2]

array([10,  8,  6,  4])

In [98]:
arr1=np.random.randint(2,100,20).reshape(5,4)

In [100]:
arr1[0:3]

array([[39, 26, 13, 16],
       [90, 50, 63, 57],
       [21, 66, 30, 20]])

In [101]:
arr1[0:3,0:3]

array([[39, 26, 13],
       [90, 50, 63],
       [21, 66, 30]])

In [102]:
arr1

array([[39, 26, 13, 16],
       [90, 50, 63, 57],
       [21, 66, 30, 20],
       [84, 84, 80, 62],
       [42,  6, 48, 91]])

In [103]:
arr1[3:,1:]

array([[84, 80, 62],
       [ 6, 48, 91]])

In [104]:
arr1[2:4,1:3]

array([[66, 30],
       [84, 80]])

In [107]:
arr1[-3:-2]

array([[21, 66, 30, 20]])

In [125]:
#Universal functions
arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))

In [120]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [124]:
arr2

array([[29, 32, 34],
       [32, 73, 68],
       [84, 59, 70]])

In [111]:
arr1+arr2

array([[113,  39,  85],
       [123,  91,  69],
       [134, 155, 150]])

In [112]:
arr1*arr2

array([[2436,  224, 1734],
       [2912, 1314,   68],
       [4200, 5664, 5600]])

In [113]:
np.sqrt(arr1)

array([[9.16515139, 2.64575131, 7.14142843],
       [9.53939201, 4.24264069, 1.        ],
       [7.07106781, 9.79795897, 8.94427191]])

In [114]:
np.exp(arr2)

array([[3.93133430e+12, 7.89629602e+13, 5.83461743e+14],
       [7.89629602e+13, 5.05239363e+31, 3.40427605e+29],
       [3.02507732e+36, 4.20121040e+25, 2.51543867e+30]])

In [115]:
np.log10(arr1)

array([[1.92427929, 0.84509804, 1.70757018],
       [1.95904139, 1.25527251, 0.        ],
       [1.69897   , 1.98227123, 1.90308999]])

In [116]:
arr1=np.arange(1,10)

In [117]:
#Broadcasting
arr1[2:]=1000

In [118]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [123]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [126]:
np.matmul(arr1,arr2)

array([[6684, 9933, 7303],
       [5424, 8784, 5568],
       [4090, 7299, 3864]])