<a href="https://colab.research.google.com/github/ramesitexp/Python_Zone/blob/main/NumpyOperationV2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4,4]

In [ ]:
type(l)

list

In [ ]:
a=np.array(l)

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a1=np.array([[1,2,3],[3,4,5]])

In [ ]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
a2=np.array([[[1,2,3],[3,4,5]]])

In [ ]:
a2

array([[[1, 2, 3],
        [3, 4, 5]]])

In [ ]:
a1.ndim

2

In [ ]:
a2.ndim

3

In [ ]:
a.ndim

1

In [ ]:
a3 = np.array([[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]]])

In [ ]:
a3.ndim

3

In [ ]:
l=  [1,2,3,4]

In [ ]:
a=np.asarray(l)

In [ ]:
m=np.matrix(l)

In [ ]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [ ]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [ ]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [ ]:
a1=a

In [ ]:
a1

array([1, 2, 3, 4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a[0]=10

In [ ]:
a1

array([10,  2,  3,  4])

In [ ]:
a

array([10,  2,  3,  4])

In [ ]:
a1[3]=50

In [ ]:
a1

array([10,  2,  3, 50])

In [ ]:
a

array([10,  2,  3, 50])

In [ ]:
a2=np.copy(a)

In [ ]:
a2[2]=30

In [ ]:
a2

array([10,  2, 30, 50])

In [ ]:
a

array([10,  2,  3, 50])

In [ ]:
np.fromfunction(lambda i,j:i==j,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [ ]:
np.random.rand(2,3)

array([[0.67257937, 0.88985323, 0.00286039],
       [0.58003813, 0.01358693, 0.43595084]])

In [ ]:
np.random.rand(2,3,2)

array([[[0.47597893, 0.66387736],
        [0.88964778, 0.0765405 ],
        [0.41277259, 0.64442278]],

       [[0.33367567, 0.17923155],
        [0.65119597, 0.46571039],
        [0.30358352, 0.91501123]]])

In [ ]:
np.random.rand(2,2,3,2)

array([[[[0.76639854, 0.69366244],
         [0.86248576, 0.36553348],
         [0.25377495, 0.13923564]],

        [[0.19285923, 0.5967344 ],
         [0.98589738, 0.80357104],
         [0.43885089, 0.05807266]]],


       [[[0.58079135, 0.87204841],
         [0.26995766, 0.01233497],
         [0.81767582, 0.48395731]],

        [[0.84928971, 0.33442847],
         [0.90890166, 0.21489038],
         [0.44528263, 0.51840344]]]])

In [ ]:
np.random.rand(3,4,4)

array([[[0.65498388, 0.41578625, 0.73430259, 0.23828998],
        [0.11745877, 0.76825278, 0.19168128, 0.41909446],
        [0.52027643, 0.48753519, 0.58247576, 0.24980416],
        [0.42838528, 0.46426414, 0.37922504, 0.33399108]],

       [[0.00988577, 0.36994046, 0.36008695, 0.36640268],
        [0.24138724, 0.01923338, 0.41328099, 0.37698032],
        [0.68823294, 0.36806657, 0.15467841, 0.42334255],
        [0.16476883, 0.24607602, 0.40277227, 0.69318233]],

       [[0.55096467, 0.16537899, 0.25714052, 0.0124914 ],
        [0.96400473, 0.55903912, 0.01619799, 0.47552578],
        [0.09631953, 0.33533362, 0.45217654, 0.31588246],
        [0.22634818, 0.52312606, 0.1030662 , 0.08065759]]])

In [ ]:
np.random.randn(3,4,4)

array([[[ 0.13082096, -0.85247781, -1.2056256 ,  0.3619295 ],
        [ 0.04784772, -1.16325601,  0.98120654,  0.16510838],
        [-0.89684454,  1.07600449,  0.13866088, -0.4425881 ],
        [ 0.83567882, -0.20922735, -0.62094677, -1.03600862]],

       [[ 0.05635817,  1.05544571,  0.21289184, -0.90232523],
        [ 0.15560723,  1.48438446, -0.19523477,  0.78569869],
        [-0.29869629,  2.02663608, -0.82873389,  1.28058707],
        [-0.12059844, -0.55271377,  0.97007378,  0.39105851]],

       [[-1.55213007, -1.168476  ,  1.55143993,  0.45648961],
        [ 0.57166462,  0.17443144,  2.10495702,  0.72214949],
        [ 0.15472969, -0.44513318,  0.10031416, -0.91784671],
        [ 0.87021347,  0.20518502,  0.67501511,  1.28706799]]])

In [ ]:
d1=np.random.randint(0,10,(4,4,2))

In [ ]:
d1

array([[[1, 8],
        [9, 0],
        [5, 2],
        [6, 6]],

       [[6, 0],
        [8, 2],
        [6, 1],
        [2, 1]],

       [[1, 4],
        [4, 2],
        [8, 1],
        [3, 0]],

       [[1, 9],
        [6, 6],
        [4, 5],
        [9, 3]]])

In [ ]:
import pandas as pd

In [ ]:
d = np.random.randn(3,4)

In [ ]:
d

array([[ 0.47049043, -0.01975685,  0.94760915,  0.32389801],
       [ 1.04216265,  0.95195079, -0.53833886, -0.99891917],
       [ 0.86055462,  0.58598714,  0.5773443 ,  1.4325888 ]])

In [ ]:
pd.DataFrame(d)

0         1         2         3
0  0.470490 -0.019757  0.947609  0.323898
1  1.042163  0.951951 -0.538339 -0.998919
2  0.860555  0.585987  0.577344  1.432589

In [ ]:
d1.reshape(8,4)

array([[1, 8, 9, 0],
       [5, 2, 6, 6],
       [6, 0, 8, 2],
       [6, 1, 2, 1],
       [1, 4, 4, 2],
       [8, 1, 3, 0],
       [1, 9, 6, 6],
       [4, 5, 9, 3]])

In [ ]:
d1.reshape(8,-1)

array([[1, 8, 9, 0],
       [5, 2, 6, 6],
       [6, 0, 8, 2],
       [6, 1, 2, 1],
       [1, 4, 4, 2],
       [8, 1, 3, 0],
       [1, 9, 6, 6],
       [4, 5, 9, 3]])