<a href="https://colab.research.google.com/github/ramesitexp/Python_Zone/blob/main/NumpyV3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
range(10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(.5,10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [ ]:
np.arange(5,-4,-.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [ ]:
np.arange(5,-4,-1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [ ]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
list(np.linspace(1,5,20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [ ]:
list(np.linspace(1,5,20,retstep=True))

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

In [ ]:
np.logspace(1,50,20)

array([1.00000000e+01, 3.79269019e+03, 1.43844989e+06, 5.45559478e+08,
       2.06913808e+11, 7.84759970e+13, 2.97635144e+16, 1.12883789e+19,
       4.28133240e+21, 1.62377674e+24, 6.15848211e+26, 2.33572147e+29,
       8.85866790e+31, 3.35981829e+34, 1.27427499e+37, 4.83293024e+39,
       1.83298071e+42, 6.95192796e+44, 2.63665090e+47, 1.00000000e+50])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
np.ones((3,4,2))*5

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [ ]:
np.empty((2,3))

array([[4.92790084e-310, 0.00000000e+000, 4.92713561e-310],
       [6.75718959e-310, 6.75718916e-310, 6.75715446e-310]])

In [ ]:
a=np.eye(4)

In [ ]:
a.shape

(4, 4)

In [ ]:
a.size

16

In [ ]:
a.ndim

2

In [ ]:
a1=np.random.randn(3,4)

In [ ]:
a1

array([[-0.29056249,  0.76121894, -1.53819484, -1.27265114],
       [-0.972809  ,  0.68206287,  2.60981366,  0.15521992],
       [ 0.82410696,  1.06630014, -0.73210111,  0.30464557]])

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(a1)

0         1         2         3
0 -0.290562  0.761219 -1.538195 -1.272651
1 -0.972809  0.682063  2.609814  0.155220
2  0.824107  1.066300 -0.732101  0.304646

In [ ]:
a1[1][1]

0.6820628666711708

In [ ]:
a1[0:2,0:2]

array([[-0.29056249,  0.76121894],
       [-0.972809  ,  0.68206287]])

In [ ]:
a1[[0,1],0:2]

array([[-0.29056249,  0.76121894],
       [-0.972809  ,  0.68206287]])

In [ ]:
a1[1:,-1]

array([0.15521992, 0.30464557])

In [ ]:
m1=np.random.randint(1,3,(3,3))

In [ ]:
m1

array([[2, 2, 1],
       [1, 2, 1],
       [2, 1, 1]])

In [ ]:
m2=np.random.randint(2,4,(3,3))

In [ ]:
m2

array([[3, 3, 2],
       [2, 3, 3],
       [3, 2, 3]])

In [ ]:
m1*m2

array([[6, 6, 2],
       [2, 6, 3],
       [6, 2, 3]])

In [ ]:
m1@m2

array([[13, 14, 13],
       [10, 11, 11],
       [11, 11, 10]])

In [ ]:
pow(m1,4)

array([[16, 16,  1],
       [ 1, 16,  1],
       [16,  1,  1]])

In [ ]:
np.sqrt(m1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.        ]])

In [ ]:
np.log(m1)

array([[0.69314718, 0.69314718, 0.        ],
       [0.        , 0.69314718, 0.        ],
       [0.69314718, 0.        , 0.        ]])

In [ ]:
np.exp(m1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183]])

In [ ]:
m1**2

array([[4, 4, 1],
       [1, 4, 1],
       [4, 1, 1]])