<a href="https://colab.research.google.com/github/ramesitexp/Python_Zone/blob/main/PandasOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
###Pandas
1. Pandas Dataframe
2. Pandas Series
3. Pandas Basic Operations

SyntaxError: invalid syntax (<ipython-input-2-9a8bfa2629bb>, line 2)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
#Create a Dataframe
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['R1','R2','R3','R4','R5'],columns=["c1","c2","c3","c4"])

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head()

c1  c2  c3  c4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [ ]:
df.head(2)

c1  c2  c3  c4
R1   0   1   2   3
R2   4   5   6   7

In [ ]:
df.tail()

c1  c2  c3  c4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [ ]:
df.tail(2)

c1  c2  c3  c4
R4  12  13  14  15
R5  16  17  18  19

In [ ]:
df.describe()

c1         c2         c3         c4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [ ]:
df[['c1','c2','c3']]

c1  c2  c3
R1   0   1   2
R2   4   5   6
R3   8   9  10
R4  12  13  14
R5  16  17  18

In [ ]:
df[['c2']]

c2
R1   1
R2   5
R3   9
R4  13
R5  17

In [ ]:
type(df[['c2']])

pandas.core.frame.DataFrame

In [ ]:
df['c1']

R1     0
R2     4
R3     8
R4    12
R5    16
Name: c1, dtype: int64

In [ ]:
type(df['c1'])

pandas.core.series.Series

In [ ]:
df.loc[["R1","R3"]]

c1  c2  c3  c4
R1   0   1   2   3
R3   8   9  10  11

In [ ]:
type(df.loc[["R1","R3"]])

pandas.core.frame.DataFrame

In [ ]:
df.iloc[0:3,0:2]

c1  c2
R1   0   1
R2   4   5
R3   8   9

In [ ]:
df

c1  c2  c3  c4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [ ]:
df.iloc[0:3,0:2]

c1  c2
R1   0   1
R2   4   5
R3   8   9

In [ ]:
df.iloc[2:4,1:3]

c2  c3
R3   9  10
R4  13  14

In [ ]:
df.iloc[2:4,1:3].values

array([[ 9, 10],
       [13, 14]])

In [ ]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["Row1","Row2"],columns=["Column1","Column2","Column3"])
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [ ]:
df.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False

In [ ]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [ ]:
df.isna().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [ ]:
df.isna()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Row1 to Row2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Column1  2 non-null      int64  
 1   Column2  1 non-null      float64
 2   Column3  2 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 172.0+ bytes


In [ ]:
type(np.nan)

float

In [ ]:
df

c1  c2  c3  c4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [ ]:
df['c1']

R1     0
R2     4
R3     8
R4    12
R5    16
Name: c1, dtype: int64

In [ ]:
df['c1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: c1, dtype: int64

In [ ]:
df['c1'].unique()

array([ 0,  4,  8, 12, 16])

In [ ]:
df['c1'].nunique()

5

In [ ]:
df=pd.DataFrame({'A':[1,2,3],'B':[1,1,1]})

In [ ]:
df

A  B
0  1  1
1  2  1
2  3  1

In [ ]:
df['A'].unique()

array([1, 2, 3])

In [ ]:
df.nunique()

A    3
B    1
dtype: int64

In [ ]:
df['B'].value_counts()

1    3
Name: B, dtype: int64

In [ ]:
df.nunique(axis=0)

A    3
B    1
dtype: int64

In [ ]:
df.nunique(axis=1)

0    1
1    2
2    2
dtype: int64

In [ ]:
df

A  B
0  1  1
1  2  1
2  3  1

In [ ]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['R1','R2','R3','R4','R5'],columns=["c1","c2","c3","c4"])

In [ ]:
df

c1  c2  c3  c4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [ ]:
df['c2']>5

R1    False
R2    False
R3     True
R4     True
R5     True
Name: c2, dtype: bool

In [ ]:
df[df['c2']>5]

c1  c2  c3  c4
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [ ]:
df

c1  c2  c3  c4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [ ]:
df[df.isnull()]

c1  c2  c3  c4
R1 NaN NaN NaN NaN
R2 NaN NaN NaN NaN
R3 NaN NaN NaN NaN
R4 NaN NaN NaN NaN
R5 NaN NaN NaN NaN

In [ ]:
df

c1  c2  c3  c4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [ ]:
df.to_csv('test.csv',index=False)

In [ ]:
df.to_excel('test1.')

In [48]:
pd.read_csv('test.csv')

c1  c2  c3  c4
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [47]:
pd.read_excel('test1.xlsx')

Unnamed: 0  c1  c2  c3  c4
0         R1   0   1   2   3
1         R2   4   5   6   7
2         R3   8   9  10  11
3         R4  12  13  14  15
4         R5  16  17  18  19

In [49]:
pd.read_csv('test.csv')

c1  c2  c3  c4
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [50]:
pd.read_csv('/content/test.csv')

c1  c2  c3  c4
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [54]:
data='{"employee_name":"Ramesh","email":"ramesitexp@gmail.com","job_profile":[{"title":"Team Lead","role":"Developer"}]}'

In [55]:
data

'{"employee_name":"Ramesh","email":"ramesitexp@gmail.com","job_profile":[{"title":"Team Lead","role":"Developer"}]}'

In [57]:
df2=pd.read_json(data)

In [58]:
df2['Salary']=100

In [59]:
df2

employee_name                 email  \
0        Ramesh  ramesitexp@gmail.com   

                                   job_profile  Salary  
0  {'title': 'Team Lead', 'role': 'Developer'}     100

In [62]:
df2['job_profile'][0]['title']

'Team Lead'

In [65]:
dict(df2['job_profile'])[0]['role']

'Developer'

In [67]:
pd.read_json(data,orient='records')

employee_name                 email  \
0        Ramesh  ramesitexp@gmail.com   

                                   job_profile  
0  {'title': 'Team Lead', 'role': 'Developer'}

In [68]:
pd.read_json(data,orient='index')

0
employee_name                                         Ramesh
email                                   ramesitexp@gmail.com
job_profile    [{'title': 'Team Lead', 'role': 'Developer'}]

In [69]:
pd.read_json(data,orient='columns')

employee_name                 email  \
0        Ramesh  ramesitexp@gmail.com   

                                   job_profile  
0  {'title': 'Team Lead', 'role': 'Developer'}

In [76]:
import pandas as pd
df=pd.DataFrame([['a','b'],['c','d']],index=['r1','r2'],columns=['col 1','col 2'])

In [77]:
df

col 1 col 2
r1     a     b
r2     c     d

In [78]:
df.to_json()

'{"col 1":{"r1":"a","r2":"c"},"col 2":{"r1":"b","r2":"d"}}'

In [79]:
df.to_json(orient='records')

'[{"col 1":"a","col 2":"b"},{"col 1":"c","col 2":"d"}]'

In [80]:
df.to_json(orient='columns')

'{"col 1":{"r1":"a","r2":"c"},"col 2":{"r1":"b","r2":"d"}}'

In [83]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

In [84]:
df.to_json(orient="index")

'{"0":{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},"1":{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},"2":{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},"3":{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},"4":{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},"5":{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},"6":{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},"7":{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.3